/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nila.bupati_bot;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nila Farihah
 */
public class formMenu extends javax.swing.JFrame {

    /**
     * Creates new form formMenu
     */
    public formMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu_user = new javax.swing.JMenuItem();
        Jmenu_member = new javax.swing.JMenuItem();
        jMenu_pesan = new javax.swing.JMenu();
        jMenuItem_pesan = new javax.swing.JMenuItem();
        jMenu_kunci = new javax.swing.JMenu();
        jMenuItem_kunci = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu BupatiBot");
        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(728, 773));

        jMenu2.setText("Kelola");

        jMenu_user.setText("User");
        jMenu_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_userActionPerformed(evt);
            }
        });
        jMenu2.add(jMenu_user);

        Jmenu_member.setText("Member");
        Jmenu_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jmenu_memberActionPerformed(evt);
            }
        });
        jMenu2.add(Jmenu_member);

        jMenuBar1.add(jMenu2);

        jMenu_pesan.setText("Pesan");
        jMenu_pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_pesanActionPerformed(evt);
            }
        });

        jMenuItem_pesan.setText("History");
        jMenuItem_pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_pesanActionPerformed(evt);
            }
        });
        jMenu_pesan.add(jMenuItem_pesan);

        jMenuBar1.add(jMenu_pesan);

        jMenu_kunci.setText("Kata Kunci");
        jMenu_kunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_kunciActionPerformed(evt);
            }
        });

        jMenuItem_kunci.setText("Kata Kunci");
        jMenuItem_kunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_kunciActionPerformed(evt);
            }
        });
        jMenu_kunci.add(jMenuItem_kunci);

        jMenuBar1.add(jMenu_kunci);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_userActionPerformed
        try {
            // TODO add your handling code here:
            new FormUser().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(formMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenu_userActionPerformed

    private void Jmenu_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jmenu_memberActionPerformed
        try {
            // TODO add your handling code here:
            new FormTelegramBot().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(formMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Jmenu_memberActionPerformed

    private void jMenu_pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_pesanActionPerformed
        // TODO add your handling code here:
        new FormPesan().setVisible(true);

    }//GEN-LAST:event_jMenu_pesanActionPerformed

    private void jMenu_kunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_kunciActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu_kunciActionPerformed

    private void jMenuItem_kunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_kunciActionPerformed
        // TODO add your handling code here:
        new FormKataKunci().setVisible(true);
    }//GEN-LAST:event_jMenuItem_kunciActionPerformed

    private void jMenuItem_pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_pesanActionPerformed
        // TODO add your handling code here:
        new FormPesan().setVisible(true);

    }//GEN-LAST:event_jMenuItem_pesanActionPerformed

    public static void Call() {
        new FormLogin().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Call();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Jmenu_member;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_kunci;
    private javax.swing.JMenuItem jMenuItem_pesan;
    private javax.swing.JMenu jMenu_kunci;
    private javax.swing.JMenu jMenu_pesan;
    private javax.swing.JMenuItem jMenu_user;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables
}
