/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.safara.giftybot;

import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.telegram.telegrambots.meta.TelegramBotsApi;
import org.telegram.telegrambots.meta.exceptions.TelegramApiException;
import org.telegram.telegrambots.meta.generics.LongPollingBot;
import org.telegram.telegrambots.updatesreceivers.DefaultBotSession;

/**
 *
 * @author safara
 */
public class FormAdmin extends javax.swing.JFrame {

    // Database Credentials
    public String DB_URL = "jdbc:mysql://localhost:3306/db_giftbot";
    public String DB_USERNAME = "root";
    public String DB_PASSWORD = "";
    ResultSet rsBrg;
    Statement stm;
    private Object[][] dataTable = null;
    private String[] header = {"ChatID", "Username"};
    private GiftBot chatbot;

    /**
     * Creates new form FormAdmin2
     */
    public FormAdmin() {
        initComponents();

        // Inisialisasi objek Chatbot
        chatbot = new GiftBot();

        bacaData_member();

        bacaData_user();

        bacaData_kunci();

        bacaMember();

        bacaUser();

        bacaPesan();

        tabelMember.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                setField();
            }

            private void setField() {
                int row = tabelMember.getSelectedRow();
                txtChat_member.setText((String) tabelMember.getValueAt(row, 0));
                txtUsername_member.setText((String) tabelMember.getValueAt(row, 1));
            }
        });

        tabelUser.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                setField_user();
            }

            private void setField_user() {
                int row = tabelUser.getSelectedRow();

                txtChat_user.setText((String) tabelUser.getValueAt(row, 0));
                txtUsername_user.setText((String) tabelUser.getValueAt(row, 1));
            }
        });

        tabelKataKunci.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                setField();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnEdit_user = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnClear_user = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUsername_user = new javax.swing.JTextField();
        btnHapus_user = new javax.swing.JButton();
        btnRefresh_user = new javax.swing.JButton();
        txtChat_user = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelUser = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnDaftar_user = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnEdit_member = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnClear_member = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUsername_member = new javax.swing.JTextField();
        btnHapus_member = new javax.swing.JButton();
        btnRefresh_member = new javax.swing.JButton();
        txtChat_member = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelMember = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnDaftar_member = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnBroadcastTo = new javax.swing.JButton();
        cmbMember = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnBroadcast = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBroadcast = new javax.swing.JTextArea();
        btnRefresh2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDatabase = new javax.swing.JButton();
        btnKeluar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPesanMasukKeluar = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        btnDaftar = new javax.swing.JButton();
        txtDescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPesan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        txtLink = new javax.swing.JTextField();
        btnKeluar1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtKata = new javax.swing.JTextField();
        btnRefresh1 = new javax.swing.JButton();
        jComboBox_gender = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelKataKunci = new javax.swing.JTable();
        jComboBox_gender1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEdit_user.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnEdit_user.setText("Edit");
        btnEdit_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit_userActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel4.setText("Kelola User");

        btnClear_user.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnClear_user.setText("Clear");
        btnClear_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear_userActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel10.setText("Username");

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel11.setText("Data User");

        txtUsername_user.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        txtUsername_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername_userActionPerformed(evt);
            }
        });

        btnHapus_user.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnHapus_user.setText("Hapus");
        btnHapus_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus_userActionPerformed(evt);
            }
        });

        btnRefresh_user.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnRefresh_user.setText("Refresh");
        btnRefresh_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh_userActionPerformed(evt);
            }
        });

        txtChat_user.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N

        tabelUser.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        tabelUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Chat ID"
            }
        ));
        jScrollPane5.setViewportView(tabelUser);

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel12.setText("Chat ID");

        btnDaftar_user.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnDaftar_user.setText("Daftar");
        btnDaftar_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftar_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUsername_user, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(btnDaftar_user, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnClear_user, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(txtChat_user, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(42, 42, 42)))
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addComponent(btnHapus_user, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit_user, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefresh_user)))
                        .addGap(20, 20, 20))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtUsername_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtChat_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear_user)
                            .addComponent(btnDaftar_user))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus_user)
                            .addComponent(btnEdit_user)
                            .addComponent(btnRefresh_user))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User", jPanel7);

        btnEdit_member.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnEdit_member.setText("Edit");
        btnEdit_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit_memberActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel3.setText("Kelola Member");

        btnClear_member.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnClear_member.setText("Clear");
        btnClear_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear_memberActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel6.setText("Username");

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel7.setText("Data Member");

        txtUsername_member.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        txtUsername_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername_memberActionPerformed(evt);
            }
        });

        btnHapus_member.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnHapus_member.setText("Hapus");
        btnHapus_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus_memberActionPerformed(evt);
            }
        });

        btnRefresh_member.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnRefresh_member.setText("Refresh");
        btnRefresh_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh_memberActionPerformed(evt);
            }
        });

        txtChat_member.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N

        tabelMember.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        tabelMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Chat ID"
            }
        ));
        jScrollPane4.setViewportView(tabelMember);

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel8.setText("Chat ID");

        btnDaftar_member.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnDaftar_member.setText("Daftar");
        btnDaftar_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftar_memberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUsername_member, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(btnDaftar_member, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnClear_member, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(txtChat_member, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(42, 42, 42)))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnHapus_member, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit_member, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefresh_member)))
                        .addGap(20, 20, 20))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtUsername_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtChat_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear_member)
                            .addComponent(btnDaftar_member))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus_member)
                            .addComponent(btnEdit_member)
                            .addComponent(btnRefresh_member))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Member", jPanel1);

        btnBroadcastTo.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnBroadcastTo.setText("Broadcast To");
        btnBroadcastTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBroadcastToActionPerformed(evt);
            }
        });

        cmbMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMemberActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel9.setText("Broadcast Pesan");

        btnBroadcast.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnBroadcast.setText("Broadcast All");
        btnBroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBroadcastActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(255, 51, 51));
        btnKeluar.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        txtBroadcast.setColumns(20);
        txtBroadcast.setRows(5);
        txtBroadcast.setMargin(new java.awt.Insets(6, 6, 6, 6));
        jScrollPane2.setViewportView(txtBroadcast);

        btnRefresh2.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnRefresh2.setText("Refresh");
        btnRefresh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(616, 616, 616)
                        .addComponent(btnRefresh2))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(btnBroadcastTo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmbMember, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(302, 302, 302)
                            .addComponent(btnBroadcast, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnKeluar))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnRefresh2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBroadcast)
                    .addComponent(cmbMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBroadcastTo)
                    .addComponent(btnKeluar))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Broadcast", jPanel3);

        btnRefresh.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel1.setText("Pesan Masuk dan Keluar");

        btnDatabase.setBackground(new java.awt.Color(255, 204, 204));
        btnDatabase.setFont(new java.awt.Font("Poppins Medium", 1, 15)); // NOI18N
        btnDatabase.setText("Database Pesan");
        btnDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatabaseActionPerformed(evt);
            }
        });

        btnKeluar2.setBackground(new java.awt.Color(255, 51, 51));
        btnKeluar2.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnKeluar2.setText("Keluar");
        btnKeluar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluar2ActionPerformed(evt);
            }
        });

        txtPesanMasukKeluar.setColumns(20);
        txtPesanMasukKeluar.setRows(5);
        jScrollPane1.setViewportView(txtPesanMasukKeluar);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 476, Short.MAX_VALUE)
                                .addComponent(btnRefresh)
                                .addGap(18, 18, 18)
                                .addComponent(btnKeluar2)))
                        .addGap(22, 22, 22))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDatabase)
                    .addComponent(btnRefresh)
                    .addComponent(btnKeluar2))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("History", jPanel2);

        btnDaftar.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnDaftar.setText("Daftar");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        txtDescription.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel2.setText("Kelola Kata Kunci");

        txtPesan.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        txtPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesanActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel13.setText("Nama Produk");

        btnClear.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel14.setText("Jenis Kelamin");

        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel15.setText("Deskripsi");

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel5.setText("Data Kata Kunci");

        btnHapus.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel16.setText("Umur");

        btnEdit.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtLink.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        txtLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkActionPerformed(evt);
            }
        });

        btnKeluar1.setBackground(new java.awt.Color(255, 102, 102));
        btnKeluar1.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnKeluar1.setText("Keluar");
        btnKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluar1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel17.setText("Link");

        jLabel18.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel18.setText("Kata");

        txtKata.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        txtKata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKataActionPerformed(evt);
            }
        });

        btnRefresh1.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnRefresh1.setText("Refresh");
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });

        jComboBox_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "female", "male" }));
        jComboBox_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_genderActionPerformed(evt);
            }
        });

        tabelKataKunci.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        tabelKataKunci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kata", "Aksi", "Jenis Kelamin", "Umur", "Link", "Nama Produk", "Deskripsi"
            }
        ));
        jScrollPane6.setViewportView(tabelKataKunci);

        jScrollPane3.setViewportView(jScrollPane6);

        jComboBox_gender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "16_25", "26_35", "36_45", "46_plus" }));
        jComboBox_gender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_gender1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel19.setText("Pesan");

        txtProductName.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        txtProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtKata, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPesan, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(jComboBox_gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_gender1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(btnRefresh1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKeluar1)))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtKata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jComboBox_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jComboBox_gender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDaftar)
                    .addComponent(btnClear)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnKeluar1)
                    .addComponent(btnRefresh1))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Kelola Kata Kunci", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEdit_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit_memberActionPerformed
        // TODO add your handling code here:
        String tChat = txtChat_member.getText();
        String tUsername = txtUsername_member.getText();

        if (!tChat.isEmpty() && !tUsername.isEmpty()) {
            try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
                String sql = "UPDATE member SET username=? WHERE chat_id=?";
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.setString(1, tUsername);
                statement.setString(2, tChat);
                statement.executeUpdate();
                statement.close();

                JOptionPane.showMessageDialog(null, "Member updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

                bacaData_member(); // Refresh tabel member
                clearMemberFields(); // Clear form fields
                bacaMember(); // Refresh combobox data list

            } catch (SQLException exception) {
                JOptionPane.showMessageDialog(null, "Error updating member: " + exception.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in both Chat ID and Username fields.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEdit_memberActionPerformed

    private void clearMemberFields() {
        txtChat_member.setText("");
        txtUsername_member.setText("");
    }

    private void btnClear_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear_memberActionPerformed
        // TODO add your handling code here:
        txtChat_member.setText("");
        txtUsername_member.setText("");
    }//GEN-LAST:event_btnClear_memberActionPerformed

    private void txtUsername_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername_memberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername_memberActionPerformed

    private void btnHapus_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus_memberActionPerformed
        // TODO add your handling code here:
        /// TODO add your handling code here:
        String tChat_member = txtChat_member.getText(); // Ambil chat_id dari field txtChat_member

        if (!tChat_member.isEmpty()) {
            int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this member?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
                    String sql = "DELETE FROM member WHERE chat_id=?";
                    PreparedStatement statement = connection.prepareStatement(sql);
                    statement.setString(1, tChat_member);
                    statement.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Member deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

                    bacaData_member(); // Refresh tabel member
                    clearMemberFields(); // Clear form fields
                    bacaMember(); // Refresh combobox data list

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error deleting member: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a member to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapus_memberActionPerformed

    private void btnRefresh_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh_memberActionPerformed
        // TODO add your handling code here:
        bacaData_member();
        cmbMember.removeAllItems();
        bacaMember();
        bacaPesan();
    }//GEN-LAST:event_btnRefresh_memberActionPerformed

    private void btnDaftar_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftar_memberActionPerformed
        // TODO add your handling code here:
        String tChat_member = txtChat_member.getText();
        String tUsername_member = txtUsername_member.getText();

        if (!tChat_member.isEmpty() && !tUsername_member.isEmpty()) {
            try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
                String sql = "INSERT INTO member (chat_id, username) VALUES (?, ?)";
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.setString(1, tChat_member);
                statement.setString(2, tUsername_member);
                statement.executeUpdate();
                statement.close();

                JOptionPane.showMessageDialog(null, "Member added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

                bacaData_member(); // Refresh tabel member
                clearMemberFields(); // Clear form fields
                bacaMember(); // Refresh combobox data list

            } catch (SQLException exception) {
                JOptionPane.showMessageDialog(null, "Error adding member: " + exception.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in both Chat ID and Username fields.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDaftar_memberActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
//        // TODO add your handling code here:
//        // Refresh tabel data
//        bacaData();
//        cmbMember.removeAllItems();
//        bacaMember();
        bacaPesan();
//        bacaData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatabaseActionPerformed
        // TODO add your handling code here:
        new FormPesan().setVisible(true);
    }//GEN-LAST:event_btnDatabaseActionPerformed

    private void btnKeluar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluar2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluar2ActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnBroadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBroadcastActionPerformed
        // TODO add your handling code here:
        String broadcastMessage = txtBroadcast.getText();

        chatbot.sendBroadcastAll(broadcastMessage);
    }//GEN-LAST:event_btnBroadcastActionPerformed

    private void cmbMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMemberActionPerformed
        // TODO add your handling code here:1441574211
    }//GEN-LAST:event_cmbMemberActionPerformed

    private void btnBroadcastToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBroadcastToActionPerformed
        // TODO add your handling code here:
        String tMember = cmbMember.getSelectedItem().toString();
        String broadcastMessage = txtBroadcast.getText();

        chatbot.sendBroadcastTo(tMember, broadcastMessage);
    }//GEN-LAST:event_btnBroadcastToActionPerformed

    private void btnEdit_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit_userActionPerformed
        // TODO add your handling code here:
        String tChat = txtChat_user.getText();
        String tUsername = txtUsername_user.getText();
        if (!tChat.isEmpty() && !tUsername.isEmpty()) {
            try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
                String sql = "UPDATE user SET username=? WHERE chat_id=?";
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.setString(1, tUsername);
                statement.setString(2, tChat);
                statement.executeUpdate();
                statement.close();

                // Refresh tabel data
                bacaData_user();

                // Refresh combobox data list
                cmbMember.removeAllItems();
                bacaMember();

                JOptionPane.showMessageDialog(null, "User updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException exception) {
                JOptionPane.showMessageDialog(null, "Error updating user: " + exception.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in both Chat ID and Username fields.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEdit_userActionPerformed

    private void btnClear_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear_userActionPerformed
        // TODO add your handling code here:
        txtChat_user.setText("");
        txtUsername_user.setText("");    }//GEN-LAST:event_btnClear_userActionPerformed

    private void txtUsername_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername_userActionPerformed
// TODO add your handling code here:
        String tChat_user = txtChat_user.getText(); // Ambil chat_id dari field txtChat_user

        if (!tChat_user.isEmpty()) {
            int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this user?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
                    String sql = "DELETE FROM user WHERE chat_id=?";
                    PreparedStatement statement = connection.prepareStatement(sql);
                    statement.setString(1, tChat_user);
                    statement.executeUpdate();

                    JOptionPane.showMessageDialog(null, "User deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

                    bacaData_user(); // Refresh tabel user
                    clearUserFields(); // Clear form fields
                    bacaUser(); // Refresh combobox data list

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error deleting user: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a user to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_txtUsername_userActionPerformed

    private void clearUserFields() {
        txtChat_user.setText("");
        txtUsername_user.setText("");
    }

    private void btnHapus_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus_userActionPerformed
// TODO add your handling code here:
        String tChat_user = txtChat_user.getText(); // Ambil chat_id dari field txtChat_user

        if (!tChat_user.isEmpty()) {
            int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this user?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
                    String sql = "DELETE FROM user WHERE chat_id=?";
                    PreparedStatement statement = connection.prepareStatement(sql);
                    statement.setString(1, tChat_user);
                    statement.executeUpdate();

                    JOptionPane.showMessageDialog(null, "User deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

                    bacaData_user(); // Refresh tabel user
                    clearUserFields(); // Clear form fields
                    bacaUser(); // Refresh combobox data list

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error deleting user: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a user to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_btnHapus_userActionPerformed

    private void btnRefresh_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh_userActionPerformed
        // TODO add your handling code here:
        bacaData_user();
        bacaPesan();    }//GEN-LAST:event_btnRefresh_userActionPerformed

    private void btnDaftar_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftar_userActionPerformed
        // TODO add your handling code here:
        String tChat = txtChat_user.getText();
        String tUsername = txtUsername_user.getText();
        if (!tChat.isEmpty() && !tUsername.isEmpty()) {
            try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
                String sql = "INSERT INTO user (chat_id, username) VALUES (?, ?)";
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.setString(1, tChat);
                statement.setString(2, tUsername);
                statement.executeUpdate();
                statement.close();

                // Refresh tabel data
                bacaData_user();

                JOptionPane.showMessageDialog(null, "User added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException exception) {
                JOptionPane.showMessageDialog(null, "Error adding user: " + exception.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in both Chat ID and Username fields.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDaftar_userActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        String tKata = txtKata.getText();
        String tPesan = txtPesan.getText();
        String tLink = txtLink.getText();
        String tProductName = txtProductName.getText();
        String tDescription = txtDescription.getText();

        // Mengambil nilai gender dari jComboBox_gender
        String tGender = jComboBox_gender.getSelectedItem().toString();

        // Mengambil nilai age group dari jComboBox_gender1
        String tAge = jComboBox_gender1.getSelectedItem().toString();

        if (!tKata.isEmpty() && !tPesan.isEmpty() && !tGender.equals("Select") && !tAge.equals("Select")) {
            try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
                String sql = "INSERT INTO keywords (keyword, message, gender, age_group, link, product_name, description) VALUES (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.setString(1, tKata);
                statement.setString(2, tPesan);
                statement.setString(3, tGender);
                statement.setString(4, tAge);
                statement.setString(5, tLink);
                statement.setString(6, tProductName);
                statement.setString(7, tDescription);

                statement.executeUpdate();
                statement.close();

                // Kosongkan field input setelah penyimpanan berhasil
                txtKata.setText("");
                txtPesan.setText("");
                txtLink.setText("");
                txtProductName.setText("");
                txtDescription.setText("");
                jComboBox_gender.setSelectedIndex(0); // Kembali ke pilihan default
                jComboBox_gender1.setSelectedIndex(0); // Kembali ke pilihan default

                // Refresh atau baca data kembali jika perlu
                bacaData_kunci(); // Metode untuk membaca dan menampilkan kembali data

                JOptionPane.showMessageDialog(null, "Data berhasil disimpan.");
            } catch (SQLException exception) {
                JOptionPane.showMessageDialog(null, "Gagal menyimpan data:\n" + exception.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi semua kolom yang diperlukan.");
        }
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void txtPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        // Membersihkan atau mengosongkan semua teks pada komponen input
        txtKata.setText("");
        txtPesan.setText("");
        txtProductName.setText("");
        txtDescription.setText("");

        // Mengosongkan pilihan pada combo box
        jComboBox_gender.setSelectedIndex(0); // Memilih "Select"
        jComboBox_gender1.setSelectedIndex(0); // Memilih "Select"

        // Mengosongkan teks pada input tambahan jika ada
        //        txtGender.setText("");
        //        txtAge.setText("");
        txtLink.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
            String sql = "DELETE FROM keywords WHERE message = ?";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, txtPesan.getText()); // Menggunakan nilai dari txtPesan untuk parameter

            int rowsDeleted = statement.executeUpdate();
            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan untuk dihapus.");
            }

            // Refresh tabel data
            bacaData_kunci();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String tKata = txtKata.getText();
        String tPesan = txtPesan.getText();
        String tLink = txtLink.getText();
        String tProductName = txtProductName.getText();
        String tDescription = txtDescription.getText();

        // Mengambil nilai gender dari jComboBox_gender
        String tGender = jComboBox_gender.getSelectedItem().toString();

        // Mengambil nilai age group dari jComboBox_gender1
        String tAge = jComboBox_gender1.getSelectedItem().toString();

        if (!tKata.isEmpty() && !tPesan.isEmpty() && !tGender.equals("Select") && !tAge.equals("Select")) {
            try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
                String sql = "UPDATE keywords SET message=?, gender=?, age_group=?, link=?, product_name=?, description=? WHERE keyword=?";
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.setString(1, tPesan);
                statement.setString(2, tGender);
                statement.setString(3, tAge);
                statement.setString(4, tLink);
                statement.setString(5, tProductName);
                statement.setString(6, tDescription);
                statement.setString(7, tKata);

                statement.executeUpdate();
                statement.close();

                // Refresh tabel data
                bacaData_kunci();
            } catch (SQLException exception) {
                JOptionPane.showMessageDialog(null, exception);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi semua kolom yang diperlukan.");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkActionPerformed

    private void btnKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluar1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluar1ActionPerformed

    private void txtKataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKataActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
        // Refresh tabel data
        bacaData_kunci();
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void jComboBox_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_genderActionPerformed

    private void jComboBox_gender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_gender1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_gender1ActionPerformed

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void btnRefresh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh2ActionPerformed
        // TODO add your handling code here:
        bacaData_kunci();

    }//GEN-LAST:event_btnRefresh2ActionPerformed

    private void setField() {
        int selectedRow = tabelKataKunci.getSelectedRow();

        if (selectedRow != -1) { // Pastikan baris yang dipilih valid
            txtKata.setText((String) tabelKataKunci.getValueAt(selectedRow, 0));
            txtPesan.setText((String) tabelKataKunci.getValueAt(selectedRow, 1));
            txtProductName.setText((String) tabelKataKunci.getValueAt(selectedRow, 5));
            txtDescription.setText((String) tabelKataKunci.getValueAt(selectedRow, 6));

            // Menetapkan nilai untuk combo box gender
            String genderValue = (String) tabelKataKunci.getValueAt(selectedRow, 2);
            if (genderValue != null && !genderValue.isEmpty()) {
                jComboBox_gender.setSelectedItem(genderValue);
            } else {
                jComboBox_gender.setSelectedIndex(0); // Pilih "Select" jika null atau kosong
            }

            // Menetapkan nilai untuk combo box age group
            String ageValue = (String) tabelKataKunci.getValueAt(selectedRow, 3);
            if (ageValue != null && !ageValue.isEmpty()) {
                jComboBox_gender1.setSelectedItem(ageValue);
            } else {
                jComboBox_gender1.setSelectedIndex(0); // Pilih "Select" jika null atau kosong
            }

            txtLink.setText((String) tabelKataKunci.getValueAt(selectedRow, 4));
        } else {
            // Jika tidak ada baris yang dipilih, kosongkan semua input
            txtKata.setText("");
            txtPesan.setText("");
            txtProductName.setText("");
            txtDescription.setText("");
            jComboBox_gender.setSelectedIndex(0); // Pilih "Select"
            jComboBox_gender1.setSelectedIndex(0); // Pilih "Select"
            txtLink.setText("");
        }
    }

    private String[] header_kunci = {"Kata", "Pesan", "Gender", "Age", "Link", "Nama Produk", "Deskripsi"};

    // method baca data dari Mysql dimasukkan ke table pada form
    private void bacaData_kunci() {
        try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
            stm = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rsBrg = stm.executeQuery("SELECT * FROM keywords");
            ResultSetMetaData meta = rsBrg.getMetaData();
            int col = meta.getColumnCount();

            // Hitung jumlah baris dalam ResultSet
            rsBrg.last(); // Pindah ke baris terakhir
            int baris = rsBrg.getRow(); // Ambil nomor baris terakhir
            rsBrg.beforeFirst(); // Pindah kembali ke baris pertama

            // Buat ulang dataTable dengan ukuran yang tepat
            dataTable = new Object[baris][col];

            // Isi dataTable dengan data dari ResultSet
            int x = 0;
            while (rsBrg.next()) {
                dataTable[x][0] = rsBrg.getString("keyword");
                dataTable[x][1] = rsBrg.getString("message");
                dataTable[x][2] = rsBrg.getString("gender");
                dataTable[x][3] = rsBrg.getString("age_group");
                dataTable[x][4] = rsBrg.getString("link");
                dataTable[x][5] = rsBrg.getString("product_name");
                dataTable[x][6] = rsBrg.getString("description");
                x++;
            }

            // Set model tabel dengan data yang baru
            DefaultTableModel model = new DefaultTableModel(dataTable, header_kunci);
            tabelKataKunci.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void bacaData_member() {
        try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
            stm = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rsBrg = stm.executeQuery("SELECT * FROM member");

            int baris = 0;
            if (rsBrg.last()) {
                baris = rsBrg.getRow();
                rsBrg.beforeFirst();
            }

            dataTable = new Object[baris][header.length];
            int x = 0;
            while (rsBrg.next()) {
                dataTable[x][0] = rsBrg.getString("chat_id");
                dataTable[x][1] = rsBrg.getString("username");
                x++;
            }

            tabelMember.setModel(new DefaultTableModel(dataTable, header));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error fetching member data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void bacaData_user() {
        try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
            stm = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rsBrg = stm.executeQuery("SELECT * FROM user");

            int baris = 0;
            if (rsBrg.last()) {
                baris = rsBrg.getRow();
                rsBrg.beforeFirst();
            }

            dataTable = new Object[baris][header.length];
            int x = 0;
            while (rsBrg.next()) {
                dataTable[x][0] = rsBrg.getString("chat_id");
                dataTable[x][1] = rsBrg.getString("username");
                x++;
            }

            tabelUser.setModel(new DefaultTableModel(dataTable, header));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error fetching user data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void bacaUser() {
        cmbMember.removeAllItems(); // Clear combobox items

        try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD); Statement statement = connection.createStatement()) {

            ResultSet rs = statement.executeQuery("SELECT * FROM user");
            while (rs.next()) {
                cmbMember.addItem(rs.getString("username").trim());
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error fetching user data for combobox: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void bacaMember() {
        cmbMember.removeAllItems(); // Clear combobox items

        try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD); Statement statement = connection.createStatement()) {

            ResultSet rs = statement.executeQuery("SELECT * FROM member");
            while (rs.next()) {
                cmbMember.addItem(rs.getString("username").trim());
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error fetching member data for combobox: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void bacaPesan() {
        List<String> messages = new ArrayList<>(); // Store messages in a list

        try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD); Statement statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY); ResultSet rs = statement.executeQuery("SELECT * FROM pesan")) {

            rs.beforeFirst();
            while (rs.next()) {
                String message = "(" + rs.getString(2).trim() + ")" + rs.getString(3).trim() + ": " + rs.getString(4).trim();
                messages.add(message); // Add each message to the list
            }
        } catch (SQLException e) {
            System.out.println("Error: " + e);
        }

        // Display messages in the text area
        SwingUtilities.invokeLater(() -> {
            for (String message : messages) {
                txtPesanMasukKeluar.append(message + "\n");
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>
        try {
            // Create an instance of the TelegramBotsApi to register your bot
            TelegramBotsApi botsApi = new TelegramBotsApi(DefaultBotSession.class
            );

            // Register your bot by providing an instance of your bot class
            botsApi.registerBot((LongPollingBot) new GiftBot());

            System.out.println("Bot started successfully!");
        } catch (TelegramApiException e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true); // Display the login form first
            }
        });
    }

    public static void Call() {
        new FormLogin().setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBroadcast;
    private javax.swing.JButton btnBroadcastTo;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear_member;
    private javax.swing.JButton btnClear_user;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnDaftar_member;
    private javax.swing.JButton btnDaftar_user;
    private javax.swing.JButton btnDatabase;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEdit_member;
    private javax.swing.JButton btnEdit_user;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapus_member;
    private javax.swing.JButton btnHapus_user;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKeluar1;
    private javax.swing.JButton btnKeluar2;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnRefresh2;
    private javax.swing.JButton btnRefresh_member;
    private javax.swing.JButton btnRefresh_user;
    private javax.swing.JComboBox<String> cmbMember;
    private javax.swing.JComboBox<String> jComboBox_gender;
    private javax.swing.JComboBox<String> jComboBox_gender1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelKataKunci;
    private javax.swing.JTable tabelMember;
    private javax.swing.JTable tabelUser;
    private javax.swing.JTextArea txtBroadcast;
    private javax.swing.JTextField txtChat_member;
    private javax.swing.JTextField txtChat_user;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtKata;
    private javax.swing.JTextField txtLink;
    private javax.swing.JTextField txtPesan;
    private javax.swing.JTextArea txtPesanMasukKeluar;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtUsername_member;
    private javax.swing.JTextField txtUsername_user;
    // End of variables declaration//GEN-END:variables

}
