/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.safara.giftybot;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author safara
 */
public class FormKataKunci extends javax.swing.JFrame {

    // Database Credentials
    public String DB_URL = "jdbc:mysql://localhost:3306/db_giftbot";
    public String DB_USERNAME = "root";
    public String DB_PASSWORD = "";
    ResultSet rsBrg;
    Statement stm;
    private Object[][] dataTable = null;
    private String[] header = {"Kata", "Pesan", "Gender", "Age", "Link", "Nama Produk", "Deskripsi"};

    /**
     * Creates new form FormKataKunci
     */
    public FormKataKunci() {
        initComponents();

        bacaData();

        // mouse click tabel barang
        tabelKataKunci.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                setField();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtKata = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnDaftar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKataKunci = new javax.swing.JTable();
        txtPesan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLink = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_gender = new javax.swing.JComboBox<>();
        jComboBox_gender1 = new javax.swing.JComboBox<>();
        txtProductName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtKata.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        txtKata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKataActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel5.setText("Pesan");

        btnDaftar.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnDaftar.setText("Daftar");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel1.setText("Kelola Kata Kunci");

        btnClear.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel2.setText("Data Kata Kunci");

        btnHapus.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(255, 102, 102));
        btnKeluar.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel4.setText("Kata");

        btnRefresh.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tabelKataKunci.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        tabelKataKunci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kata", "Aksi", "Jenis Kelamin", "Umur", "Link", "Nama Produk", "Deskripsi"
            }
        ));
        jScrollPane1.setViewportView(tabelKataKunci);

        jScrollPane2.setViewportView(jScrollPane1);

        txtPesan.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        txtPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel6.setText("Jenis Kelamin");

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel7.setText("Umur");

        txtLink.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        txtLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel8.setText("Link");

        jComboBox_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "female", "male" }));
        jComboBox_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_genderActionPerformed(evt);
            }
        });

        jComboBox_gender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "16_25", "26_35", "36_45", "46_plus" }));
        jComboBox_gender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_gender1ActionPerformed(evt);
            }
        });

        txtProductName.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        txtProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductNameActionPerformed(evt);
            }
        });

        txtDescription.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel9.setText("Nama Produk");

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel10.setText("Deskripsi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtKata, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPesan, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(jComboBox_gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_gender1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKeluar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtKata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox_gender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDaftar)
                    .addComponent(btnClear)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnKeluar)
                    .addComponent(btnRefresh))
                .addGap(32, 32, 32))
        );

        getAccessibleContext().setAccessibleName("WeatherBot - Restu Lestari");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        String tKata = txtKata.getText();
        String tPesan = txtPesan.getText();
        String tLink = txtLink.getText();
        String tProductName = txtProductName.getText();
        String tDescription = txtDescription.getText();

        // Mengambil nilai gender dari jComboBox_gender
        String tGender = jComboBox_gender.getSelectedItem().toString();

        // Mengambil nilai age group dari jComboBox_gender1
        String tAge = jComboBox_gender1.getSelectedItem().toString();

        if (!tKata.isEmpty() && !tPesan.isEmpty() && !tGender.equals("Select") && !tAge.equals("Select")) {
            try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
                String sql = "INSERT INTO keywords (keyword, message, gender, age_group, link, product_name, description) VALUES (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.setString(1, tKata);
                statement.setString(2, tPesan);
                statement.setString(3, tGender);
                statement.setString(4, tAge);
                statement.setString(5, tLink);
                statement.setString(6, tProductName);
                statement.setString(7, tDescription);

                statement.executeUpdate();
                statement.close();

                // Kosongkan field input setelah penyimpanan berhasil
                txtKata.setText("");
                txtPesan.setText("");
                txtLink.setText("");
                txtProductName.setText("");
                txtDescription.setText("");
                jComboBox_gender.setSelectedIndex(0); // Kembali ke pilihan default
                jComboBox_gender1.setSelectedIndex(0); // Kembali ke pilihan default

                // Refresh atau baca data kembali jika perlu
                bacaData(); // Metode untuk membaca dan menampilkan kembali data

                JOptionPane.showMessageDialog(null, "Data berhasil disimpan.");
            } catch (SQLException exception) {
                JOptionPane.showMessageDialog(null, "Gagal menyimpan data:\n" + exception.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi semua kolom yang diperlukan.");
        }
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String tKata = txtKata.getText();
        String tPesan = txtPesan.getText();
        String tLink = txtLink.getText();
        String tProductName = txtProductName.getText();
        String tDescription = txtDescription.getText();

        // Mengambil nilai gender dari jComboBox_gender
        String tGender = jComboBox_gender.getSelectedItem().toString();

        // Mengambil nilai age group dari jComboBox_gender1
        String tAge = jComboBox_gender1.getSelectedItem().toString();

        if (!tKata.isEmpty() && !tPesan.isEmpty() && !tGender.equals("Select") && !tAge.equals("Select")) {
            try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
                String sql = "UPDATE keywords SET message=?, gender=?, age_group=?, link=?, product_name=?, description=? WHERE keyword=?";
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.setString(1, tPesan);
                statement.setString(2, tGender);
                statement.setString(3, tAge);
                statement.setString(4, tLink);
                statement.setString(5, tProductName);
                statement.setString(6, tDescription);
                statement.setString(7, tKata);

                statement.executeUpdate();
                statement.close();

                // Refresh tabel data
                bacaData();
            } catch (SQLException exception) {
                JOptionPane.showMessageDialog(null, exception);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi semua kolom yang diperlukan.");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtKataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKataActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        // Membersihkan atau mengosongkan semua teks pada komponen input
        txtKata.setText("");
        txtPesan.setText("");
        txtProductName.setText("");
        txtDescription.setText("");

        // Mengosongkan pilihan pada combo box
        jComboBox_gender.setSelectedIndex(0); // Memilih "Select"
        jComboBox_gender1.setSelectedIndex(0); // Memilih "Select"

        // Mengosongkan teks pada input tambahan jika ada
//        txtGender.setText("");
//        txtAge.setText("");
        txtLink.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        // Refresh tabel data
        bacaData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
            String sql = "delete from keywords where keyword='" + txtKata.getText() + "'";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.executeUpdate(sql);

            // Refresh tabel data
            bacaData();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkActionPerformed

    private void txtPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesanActionPerformed

    private void jComboBox_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_genderActionPerformed

    private void jComboBox_gender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_gender1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_gender1ActionPerformed

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    // method set field form jika salah satu field tabel ditekan
    private void setField() {
        int selectedRow = tabelKataKunci.getSelectedRow();

        if (selectedRow != -1) { // Pastikan baris yang dipilih valid
            txtKata.setText((String) tabelKataKunci.getValueAt(selectedRow, 0));
            txtPesan.setText((String) tabelKataKunci.getValueAt(selectedRow, 1));
            txtProductName.setText((String) tabelKataKunci.getValueAt(selectedRow, 5));
            txtDescription.setText((String) tabelKataKunci.getValueAt(selectedRow, 6));

            // Menetapkan nilai untuk combo box gender
            String genderValue = (String) tabelKataKunci.getValueAt(selectedRow, 2);
            if (genderValue != null && !genderValue.isEmpty()) {
                jComboBox_gender.setSelectedItem(genderValue);
            } else {
                jComboBox_gender.setSelectedIndex(0); // Pilih "Select" jika null atau kosong
            }

            // Menetapkan nilai untuk combo box age group
            String ageValue = (String) tabelKataKunci.getValueAt(selectedRow, 3);
            if (ageValue != null && !ageValue.isEmpty()) {
                jComboBox_gender1.setSelectedItem(ageValue);
            } else {
                jComboBox_gender1.setSelectedIndex(0); // Pilih "Select" jika null atau kosong
            }

            txtLink.setText((String) tabelKataKunci.getValueAt(selectedRow, 4));
        } else {
            // Jika tidak ada baris yang dipilih, kosongkan semua input
            txtKata.setText("");
            txtPesan.setText("");
            txtProductName.setText("");
            txtDescription.setText("");
            jComboBox_gender.setSelectedIndex(0); // Pilih "Select"
            jComboBox_gender1.setSelectedIndex(0); // Pilih "Select"
            txtLink.setText("");
        }
    }

    // method baca data dari Mysql dimasukkan ke table pada form
    private void bacaData() {
        try (Connection connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD)) {
            stm = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rsBrg = stm.executeQuery("select * from keywords");
            ResultSetMetaData meta = rsBrg.getMetaData();
            int col = meta.getColumnCount();
            int baris = 0;
            while (rsBrg.next()) {
                baris = rsBrg.getRow();
            }
            dataTable = new Object[baris][col];
            int x = 0;
            rsBrg.beforeFirst();
            while (rsBrg.next()) {
                dataTable[x][0] = rsBrg.getString("keyword");
                dataTable[x][1] = rsBrg.getString("message");
                dataTable[x][2] = rsBrg.getString("gender");
                dataTable[x][3] = rsBrg.getString("age_group");
                dataTable[x][4] = rsBrg.getString("link");
                dataTable[x][5] = rsBrg.getString("product_name");
                dataTable[x][6] = rsBrg.getString("description");

                x++;
            }
            tabelKataKunci.setModel(new DefaultTableModel(dataTable, header));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKataKunci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKataKunci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKataKunci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKataKunci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKataKunci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> jComboBox_gender;
    private javax.swing.JComboBox<String> jComboBox_gender1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelKataKunci;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtKata;
    private javax.swing.JTextField txtLink;
    private javax.swing.JTextField txtPesan;
    private javax.swing.JTextField txtProductName;
    // End of variables declaration//GEN-END:variables
}
